'''
    적성일 : 2023년 10월 11일
    작성자 : 202195057 손패택
    설면 : 
'''
inmport random
list1=[]
for i in range(10):
    list1.append(random.randint(10.99))
    print("随机生成的整数列表为:",list1)
    list.sort()
    print("递增排序后的列表为：",list1)
    list1.reverse()
    print("反序后的列表为："，list1)
    print("列表元素的最大值为："，max（list1))
    print("列表元素的最小值为："，min（list1))
    sum=0
    for i in list：
    sum+=
    print（"列表元素的平均值为：”，sum/len（list1))
    